<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EasyLog\EasyLog.csproj" />
    <ProjectReference Include="..\EasySave.Core\EasySave.Core.csproj" />
  </ItemGroup>

</Project>
